controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_roll_joint
      - shoulder_pitch_joint
      - elbow_roll_joint
      - elbow_pitch_joint
      - elbow_yaw_joint
      - wrist_pitch_joint
      - wrist_roll_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - gripper1_joint
      - gripper2_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: straight
  - group: gripper
    pose: open